# Site settings
title: GrowTye
email: GrowTye@gmail.com
description: Links to find more of GrowTye all over the interwebs

baseurl: "" # the subpath of your site, e.g. /blog/
url: "growtye.info" # the base hostname & protocol for your site

# User setting
owner: GrowTye
email: GrowTye@gmail.com
github_username: cvatch

  # Feel free to add more lines here 
copyright: Infinite Activities

# API settings
google_api_key: AIzaSyA8H0jVz_6Hc273rqNYKQ6AAiBvQfVKmYQ

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
